### ISSUE TITLE
api key error

### ISSUE THREAD

**Issue by lucazin** [bkhezry/weather#14]
Hi!

I have apikey and after i put in string.. and start again to test.. 
they give api key is invalid ..try next update

**Comment by bkhezry** [comment]
@lucazin Hi,
Please provide the valid API key from open weather map website and put it in this file:
https://github.com/bkhezry/weather/blob/master/app/src/main/res/values/open_weather_map_api.xml

the price of it is 40$ for each month.

**Comment by lucazin** [comment]
hi! Thanks for help me.

I see now..have a free plan.. 60 calls / minute    its a bad limit?
600 calls in minute is a good? or is poor ?

**Comment by bkhezry** [comment]
In this plan that you mentioned (free) 16 days weather didn't work. For using this project you should provide API that is not free.
