### ISSUE TITLE
خطا در دریافت 

### ISSUE THREAD

**Issue by avrpic8** [bkhezry/weather#17]
باعرض سلام و خسته نباشد
برنامه و قتی کامپایل میشه فقط دمای حال رو نشون میده و دمای چهار روز یا پانزده روز خالی هستند.
مشکل چی هست؟ نسخه نصبی درست کار می کرد.

**Comment by bkhezry** [comment]
@avrpic8 وقت بخیر.
برای استفاده از تمامی دیتای هواشناسی، نیاز به کلیدی دارید که رایگان نیست. قیمت اون ۴۰دلار در ماه است. در صورت نداشتن اون، فقط دیتای روز جاری رو می‌بینید.
در این صورت فقط از کد برنامه در جهت یادگیری می‌تونید استفاده کنید.

**Comment by avrpic8** [comment]
خیلی ممنون از پاسختون و اینکه این اپو به رایگان و متن باز در اختیار بقیه قرار دادید.
