### ISSUE TITLE
i need the code have butterknife 

### ISSUE THREAD

**Issue by ibrha** [bkhezry/weather#21]
hello brother do you have the old code please ?? 

the build gradle have like this

classpath 'com.android.tools.build:gradle:3.6.3'
        classpath 'io.objectbox:objectbox-gradle-plugin:2.5.1'
        classpath 'com.google.gms:google-services:4.3.3'
        classpath 'io.fabric.tools:gradle:1.31.2'

**Comment by bkhezry** [comment]
Hi @ibrha 
you can download a zip file of source code before remove butter knife from this URL
https://github.com/bkhezry/weather/releases/tag/2.1.0

**Comment by ibrha** [comment]
i love you dude
