### ISSUE TITLE
change package name

### ISSUE THREAD

**Issue by ibrha** [bkhezry/weather#23]
android studio 3.6.3
android : 7,8,9,10,5
when i released the apk and test it with change  package name .. the app crash and out 
when i released with same your package name the app work normal ~~!!

version of weather 2.1.0
please see the problem when you change package name and release the apk and test it write some country

**Comment by bkhezry** [comment]
I think you did not correctly change the package name and application id of the app.
https://stackoverflow.com/questions/16804093/rename-package-in-android-studio
