### ISSUE TITLE
Issue

### ISSUE THREAD

**Issue by Azmath-Ikram19** [bkhezry/weather#26]
Can you tell me how to change the degree parameters and you have implemented it in Persian numbers, i want them in normal numericals or any other language. So how do u change that and they r stored under which file ??? please help with this asap
![WhatsApp Image 2021-07-13 at 23 26 33](https://user-images.githubusercontent.com/85067445/125501896-c97f5448-f661-41cb-af2b-1215444b33bc.jpeg)

**Comment by Azmath-Ikram19** [comment]
brother please help out i just want to display normal numbers instead of
persian language there

**Comment by GoRaN909** [comment]
You can change the default app font here is it 

https://github.com/bkhezry/weather/tree/master/app/src/main/assets/fonts/Vazir.ttf

replace Vazir.ttf with another font that's all :)

**Comment by Azmath-Ikram19** [comment]
No bro not font Language there r 2 languages in this One is English and
other is Persian instead of Persian I need Hindi or Urdu so how do u do
that and the numbers as well
