### ISSUE TITLE
missing classes

### ISSUE THREAD

**Issue by Leishemba50** [bkhezry/weather#37]
missing MyObjectBox class and ItemHourlyDB_ class in db

**Comment by bkhezry** [comment]
Please clean & rebuild the app.

**Comment by MuhammadImran2** [comment]
https://www.youtube.com/watch?v=flmAeYY-u9I

**Comment by MuhammadImran2** [comment]
i am explain end of it with picture  . Please check it 
https://github.com/bkhezry/weather/issues/25
