### ISSUE TITLE
خروجی و کار با اپ هواشناسی

### ISSUE THREAD

**Issue by cyrusamirabadi** [bkhezry/weather#5]
سلام ارادتمندم
من از اپ خروجی گرفتم اما کار نمی کنه. اول این که گریدل اش روی 3.5 ست شده بود که اصلا همچین گریدلی وجود نداره
دوم این که من خروجی گرفتم و صفحه اول جستجوی شهر میاد و شهر رو که وارد می کنی، سرچ نمی کنه. آیا باید فیلترشکن روشن باشه؟

**Comment by bkhezry** [comment]
<div dir="rtl">
سلام وقت بخیر.
اگر اندروید استدیوی شما روی کانال قناری باشه و نسخه آلفا رو نصب کنید تا ۳.۶ هم الان وجود داره
برای استفاده از برنامه نیاز به کلیدی از سمت سایت OpenWeatherMap داشته باشید که اون کلید الان به ازای هر ماه ۴۰ دلار هزینه خواهد داشت. فقط می‌تونید از سورس اون استفاده کنید والا نمی‌تونید با کلید خودتون دیتا رو ببینید. موفق باشید
</div>

**Comment by cyrusamirabadi** [comment]
آره ممنون بهروز جان 
این مورد قناری رو نمی دونستم 
Thanks for your prompt reply :)
